// Generated by gencpp from file naoqi_msgs/BlinkResult.msg
// DO NOT EDIT!


#ifndef NAOQI_MSGS_MESSAGE_BLINKRESULT_H
#define NAOQI_MSGS_MESSAGE_BLINKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace naoqi_msgs
{
template <class ContainerAllocator>
struct BlinkResult_
{
  typedef BlinkResult_<ContainerAllocator> Type;

  BlinkResult_()
    : still_blinking(false)  {
    }
  BlinkResult_(const ContainerAllocator& _alloc)
    : still_blinking(false)  {
    }



   typedef uint8_t _still_blinking_type;
  _still_blinking_type still_blinking;




  typedef boost::shared_ptr< ::naoqi_msgs::BlinkResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_msgs::BlinkResult_<ContainerAllocator> const> ConstPtr;

}; // struct BlinkResult_

typedef ::naoqi_msgs::BlinkResult_<std::allocator<void> > BlinkResult;

typedef boost::shared_ptr< ::naoqi_msgs::BlinkResult > BlinkResultPtr;
typedef boost::shared_ptr< ::naoqi_msgs::BlinkResult const> BlinkResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_msgs::BlinkResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_msgs::BlinkResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace naoqi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'naoqi_msgs': ['/home/vrabaud/work/master/alrosconverter/msg/naoqi_msgs/msg', '/home/vrabaud/work/master/alrosconverter/msg/devel/share/naoqi_msgs/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_msgs::BlinkResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_msgs::BlinkResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_msgs::BlinkResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_msgs::BlinkResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_msgs::BlinkResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_msgs::BlinkResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_msgs::BlinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53e041b81450f9247036f13b3c0bf822";
  }

  static const char* value(const ::naoqi_msgs::BlinkResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53e041b81450f924ULL;
  static const uint64_t static_value2 = 0x7036f13b3c0bf822ULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_msgs::BlinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_msgs/BlinkResult";
  }

  static const char* value(const ::naoqi_msgs::BlinkResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_msgs::BlinkResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
bool still_blinking\n\
";
  }

  static const char* value(const ::naoqi_msgs::BlinkResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_msgs::BlinkResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.still_blinking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BlinkResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_msgs::BlinkResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_msgs::BlinkResult_<ContainerAllocator>& v)
  {
    s << indent << "still_blinking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.still_blinking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_MSGS_MESSAGE_BLINKRESULT_H
