// Generated by gencpp from file naoqi_msgs/CmdVelServiceRequest.msg
// DO NOT EDIT!


#ifndef NAOQI_MSGS_MESSAGE_CMDVELSERVICEREQUEST_H
#define NAOQI_MSGS_MESSAGE_CMDVELSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace naoqi_msgs
{
template <class ContainerAllocator>
struct CmdVelServiceRequest_
{
  typedef CmdVelServiceRequest_<ContainerAllocator> Type;

  CmdVelServiceRequest_()
    : twist()  {
    }
  CmdVelServiceRequest_(const ContainerAllocator& _alloc)
    : twist(_alloc)  {
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _twist_type;
  _twist_type twist;




  typedef boost::shared_ptr< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CmdVelServiceRequest_

typedef ::naoqi_msgs::CmdVelServiceRequest_<std::allocator<void> > CmdVelServiceRequest;

typedef boost::shared_ptr< ::naoqi_msgs::CmdVelServiceRequest > CmdVelServiceRequestPtr;
typedef boost::shared_ptr< ::naoqi_msgs::CmdVelServiceRequest const> CmdVelServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace naoqi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'naoqi_msgs': ['/home/vrabaud/work/master/alrosconverter/msg/naoqi_msgs/msg', '/home/vrabaud/work/master/alrosconverter/msg/devel/share/naoqi_msgs/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a787b2802160dcc7fe02d089e10afe56";
  }

  static const char* value(const ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa787b2802160dcc7ULL;
  static const uint64_t static_value2 = 0xfe02d089e10afe56ULL;
};

template<class ContainerAllocator>
struct DataType< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "naoqi_msgs/CmdVelServiceRequest";
  }

  static const char* value(const ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/Twist twist\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.twist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CmdVelServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::naoqi_msgs::CmdVelServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAOQI_MSGS_MESSAGE_CMDVELSERVICEREQUEST_H
