// Generated by gencpp from file naoqi_msgs/SetArmsEnabled.msg
// DO NOT EDIT!


#ifndef NAOQI_MSGS_MESSAGE_SETARMSENABLED_H
#define NAOQI_MSGS_MESSAGE_SETARMSENABLED_H

#include <ros/service_traits.h>


#include <naoqi_msgs/SetArmsEnabledRequest.h>
#include <naoqi_msgs/SetArmsEnabledResponse.h>


namespace naoqi_msgs
{

struct SetArmsEnabled
{

typedef SetArmsEnabledRequest Request;
typedef SetArmsEnabledResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetArmsEnabled
} // namespace naoqi_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::naoqi_msgs::SetArmsEnabled > {
  static const char* value()
  {
    return "4da9069facca935244c3405e288ba555";
  }

  static const char* value(const ::naoqi_msgs::SetArmsEnabled&) { return value(); }
};

template<>
struct DataType< ::naoqi_msgs::SetArmsEnabled > {
  static const char* value()
  {
    return "naoqi_msgs/SetArmsEnabled";
  }

  static const char* value(const ::naoqi_msgs::SetArmsEnabled&) { return value(); }
};


// service_traits::MD5Sum< ::naoqi_msgs::SetArmsEnabledRequest> should match 
// service_traits::MD5Sum< ::naoqi_msgs::SetArmsEnabled > 
template<>
struct MD5Sum< ::naoqi_msgs::SetArmsEnabledRequest>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_msgs::SetArmsEnabled >::value();
  }
  static const char* value(const ::naoqi_msgs::SetArmsEnabledRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_msgs::SetArmsEnabledRequest> should match 
// service_traits::DataType< ::naoqi_msgs::SetArmsEnabled > 
template<>
struct DataType< ::naoqi_msgs::SetArmsEnabledRequest>
{
  static const char* value()
  {
    return DataType< ::naoqi_msgs::SetArmsEnabled >::value();
  }
  static const char* value(const ::naoqi_msgs::SetArmsEnabledRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::naoqi_msgs::SetArmsEnabledResponse> should match 
// service_traits::MD5Sum< ::naoqi_msgs::SetArmsEnabled > 
template<>
struct MD5Sum< ::naoqi_msgs::SetArmsEnabledResponse>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_msgs::SetArmsEnabled >::value();
  }
  static const char* value(const ::naoqi_msgs::SetArmsEnabledResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_msgs::SetArmsEnabledResponse> should match 
// service_traits::DataType< ::naoqi_msgs::SetArmsEnabled > 
template<>
struct DataType< ::naoqi_msgs::SetArmsEnabledResponse>
{
  static const char* value()
  {
    return DataType< ::naoqi_msgs::SetArmsEnabled >::value();
  }
  static const char* value(const ::naoqi_msgs::SetArmsEnabledResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAOQI_MSGS_MESSAGE_SETARMSENABLED_H
