// Generated by gencpp from file naoqi_msgs/SetTransform.msg
// DO NOT EDIT!


#ifndef NAOQI_MSGS_MESSAGE_SETTRANSFORM_H
#define NAOQI_MSGS_MESSAGE_SETTRANSFORM_H

#include <ros/service_traits.h>


#include <naoqi_msgs/SetTransformRequest.h>
#include <naoqi_msgs/SetTransformResponse.h>


namespace naoqi_msgs
{

struct SetTransform
{

typedef SetTransformRequest Request;
typedef SetTransformResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTransform
} // namespace naoqi_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::naoqi_msgs::SetTransform > {
  static const char* value()
  {
    return "67035ddf415a9bb64191f0e45b060e35";
  }

  static const char* value(const ::naoqi_msgs::SetTransform&) { return value(); }
};

template<>
struct DataType< ::naoqi_msgs::SetTransform > {
  static const char* value()
  {
    return "naoqi_msgs/SetTransform";
  }

  static const char* value(const ::naoqi_msgs::SetTransform&) { return value(); }
};


// service_traits::MD5Sum< ::naoqi_msgs::SetTransformRequest> should match 
// service_traits::MD5Sum< ::naoqi_msgs::SetTransform > 
template<>
struct MD5Sum< ::naoqi_msgs::SetTransformRequest>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_msgs::SetTransform >::value();
  }
  static const char* value(const ::naoqi_msgs::SetTransformRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_msgs::SetTransformRequest> should match 
// service_traits::DataType< ::naoqi_msgs::SetTransform > 
template<>
struct DataType< ::naoqi_msgs::SetTransformRequest>
{
  static const char* value()
  {
    return DataType< ::naoqi_msgs::SetTransform >::value();
  }
  static const char* value(const ::naoqi_msgs::SetTransformRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::naoqi_msgs::SetTransformResponse> should match 
// service_traits::MD5Sum< ::naoqi_msgs::SetTransform > 
template<>
struct MD5Sum< ::naoqi_msgs::SetTransformResponse>
{
  static const char* value()
  {
    return MD5Sum< ::naoqi_msgs::SetTransform >::value();
  }
  static const char* value(const ::naoqi_msgs::SetTransformResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::naoqi_msgs::SetTransformResponse> should match 
// service_traits::DataType< ::naoqi_msgs::SetTransform > 
template<>
struct DataType< ::naoqi_msgs::SetTransformResponse>
{
  static const char* value()
  {
    return DataType< ::naoqi_msgs::SetTransform >::value();
  }
  static const char* value(const ::naoqi_msgs::SetTransformResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAOQI_MSGS_MESSAGE_SETTRANSFORM_H
